name: GitHub Actions Demo

on:
  [push]
  # schedule:
  #   - cron: "0 0 * * *"
jobs:
  github-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - run: npm i
      - run: touch .env
      - run: echo NOTION_KEY =${{ secrets.NOTION_KEY }} >> .env
      - run: node script.js
      - run: git config --global user.name '00MB'
      - run: git config --global user.email '00MB@users.noreply.github.com'
      - run: git commit -am "Automated report"
      - run: git push
