name: GitHub Actions Demo

on:
  [push]
  # schedule:
  #   - cron: "0 0 * * *"
jobs:
  github-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - run: npm i
      - name: create env file
      run: |
        touch .env
        echo NOTION_KEY =${{ secrets.NOTION_KEY }} >> .env
      - run: node script.js
